### ISSUE TITLE
Color schema not readable on light terminals

### ISSUE THREAD

**Issue by Toddy69** [JoseLion/pretty-jupiter#152]
The color schema is unfortunately not readable on terminals with light color schema. Would be nice, if there was an option to select a light mode via `--console=light` (like the plain option in #125). Alternatively removing explicit colors for the text and only using colors for the signalling keywords (like FAILED, PASSED, SKIPPED etc.) should work in light and dark terminals.

![image](https://github.com/JoseLion/pretty-jupiter/assets/3174167/64b1a836-6e41-4c53-b4ad-665d53fb5022)

**Comment by JoseLion** [comment]
I'm sorry for not getting back to you sooner. This is a great catch! The quickest solution would be to remove the `GRAY` color on the text. Thanks again for the feedback. It's always great to hear from people using this plugin 🙂

**Comment by JoseLion** [comment]
After carefully checking this issue, I found that the `GREY` color was not the problem. That one looks good on light terminals. The real problem is that I used a `WHITE` color for the rest of the text, which does not work on light terminals.
