### ISSUE TITLE
Cannot add extension with name 'prettyJupiter', as there is an extension already registered with that name

### ISSUE THREAD

**Issue by wyhasany** [JoseLion/pretty-jupiter#55]
First of all thank you for your amazing plugin. I have an issue while adding it to my `build.gradle.kts`. When I try to run `./gradlew test` I see following error:
```
* What went wrong:
An exception occurred applying plugin request [id: 'com.github.joselion.pretty-jupiter', version: '1.3.1']
> Failed to apply plugin 'com.github.joselion.pretty-jupiter'.
   > Cannot add extension with name 'prettyJupiter', as there is an extension already registered with that name.
```

I can provide stacktraces but they don't seem very helpfull. It seems that transitively my project includes another extension of the very same name `prettyJupiter`. Is that possible? Do you have any idea how can I fix that?

**Comment by JoseLion** [comment]
@wyhasany thanks! I'm glad you liked the plugin 🙂 

Actually, I encountered the same issue a few days ago whenever I had more than one task of type `Test` like the following:
```groovy
task.register('e2e', Test) {
  testClassesDirs = sourceSets.e2e.output.classesDirs
  classpath = sourceSets.e2e.runtimeClasspath
}
```

The plugin's extension creation was run once per each `Test` task, which apparently makes Gradle think you want to register the plugin again. So if you too have more than one `Test` task in your project, then please update to `v1.3.2`. I published a fix a few moments ago 🙂 

However, if that does not fix the issue for you, would it be possible for you to share your `build.gradle` file so I can take a deeper look?

Cheers

**Comment by wyhasany** [comment]
Wow you're pretty fast that was my case 🥇  I have two test types "test" and "integration-test". Thank you very much :)

**Comment by JoseLion** [comment]
Awesome, I'm glad it worked 🙂 happy testing!!
